name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Deploy to GitHub Pages
      if: success()
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git checkout gh-pages
        git pull origin main
        cp -r .github/workflows/PokeJavaWeb/* .
        git add .
        git commit -m "Update GitHub Pages"
        git push origin gh-pages
